import type { ParsedContract } from "@/lib/schemas/contract-parse";

export const DEMO_PARSED: ParsedContract = {
  header: {
    subject: "Development of a patient management CRM system with scheduling module, electronic health records, and billing for Suasuna Clinic.",
    parties: [
      {
        role: "Client",
        name: "Suasuna Clinic Ltd",
        identifier: "EIN 12-3456789",
        representative: "Dr. Ernani Suasuna, Clinical Director",
        city: "Recife, PE",
        initials: "SC",
      },
      {
        role: "Developer",
        name: "DevStudio Technology LLC",
        identifier: "EIN 98-7654321",
        representative: "Michael Santos, Technical Director",
        city: "Recife, PE",
        initials: "DT",
      },
    ],
    payment: {
      total: "$15,000",
      terms: "Payment divided into 4 installments tied to milestone delivery, via bank transfer, within 5 business days after approval of each milestone by the CLIENT.",
    },
    timeline: {
      start: "2026-01-15",
      end: "2026-03-26",
      durationDays: 70,
    },
    jurisdiction: "Courts of Recife, PE, Brazil",
  },
  risks: {
    risks: [
      {
        id: "r1",
        clause: "Clause 2.2",
        title: "Uncapped late penalty",
        description: "The 2% monthly penalty on the remaining balance has no maximum cap, creating unlimited financial exposure for the DEVELOPER.",
        severity: "high",
        originalText: "Delays exceeding 15 business days by the DEVELOPER shall incur a penalty of 2% per month on the remaining balance, with no maximum cap.",
        suggestion: "Add a clause capping the total penalty at no more than 20% of the contract value.",
      },
      {
        id: "r2",
        clause: "Clause 5.1",
        title: "Vague and indefinite confidentiality",
        description: "The confidentiality obligation specifies no duration and no categories of protected information, which could lead to future disputes.",
        severity: "high",
        originalText: "Both parties agree to maintain confidentiality of all information exchanged for an indefinite period, without defining what constitutes \"confidential information\".",
        suggestion: "Define an explicit duration (e.g., 2 years after termination) and list categories of sensitive information.",
      },
      {
        id: "r3",
        clause: "Clause 1.2",
        title: "Undefined milestone approval criteria",
        description: "There is no clear definition of what constitutes milestone approval, leaving room for arbitrary payment refusal.",
        severity: "high",
        originalText: "Payment shall be made via bank transfer within 5 business days after approval of each milestone by the CLIENT.",
        suggestion: "Include objective acceptance criteria and a maximum approval period (e.g., 5 business days).",
      },
      {
        id: "r4",
        clause: "Clause 2",
        title: "No force majeure clause",
        description: "The contract does not account for acts of God or force majeure events that could impact delivery timelines.",
        severity: "medium",
        originalText: "The total execution period is 70 (seventy) calendar days.",
        suggestion: "Include a standard force majeure clause with a 48-hour notification requirement.",
      },
      {
        id: "r5",
        clause: "General",
        title: "No dispute resolution mechanism",
        description: "The contract specifies jurisdiction but does not require prior mediation, which could make conflict resolution more expensive and slow.",
        severity: "medium",
        originalText: "The courts of Recife, PE, Brazil shall have exclusive jurisdiction.",
        suggestion: "Add a mandatory 30-day mediation clause before litigation.",
      },
      {
        id: "r6",
        clause: "Clause 1.2",
        title: "Payment timeline subject to subjective approval",
        description: "The 5 business days for payment only begin after approval, which has no defined deadline to occur.",
        severity: "medium",
        originalText: "within 5 business days after approval of each milestone by the CLIENT.",
        suggestion: "Establish that milestones are automatically approved if no feedback is given within 5 business days.",
      },
      {
        id: "r7",
        clause: "Clause 2.1",
        title: "Project start depends on client action",
        description: "The contract does not clearly define what constitutes the official project start, which could create disputes about when the timeline begins.",
        severity: "low",
        originalText: "starting on 01/15/2026",
        suggestion: "Add a start condition (e.g., receipt of first payment or digital signature).",
      },
    ],
  },
  milestones: {
    milestones: [
      {
        id: "m1",
        name: "Design System & Prototypes",
        value: 3000,
        deadline: "2026-01-30",
        deliverables: "Delivery of wireframes, design system, and navigable prototypes.",
      },
      {
        id: "m2",
        name: "Frontend Development",
        value: 4500,
        deadline: "2026-02-19",
        deliverables: "Implementation of screens and components.",
      },
      {
        id: "m3",
        name: "Backend & API",
        value: 5000,
        deadline: "2026-03-11",
        deliverables: "API development, database, and integrations.",
      },
      {
        id: "m4",
        name: "Deploy & Launch",
        value: 2500,
        deadline: "2026-03-26",
        deliverables: "Infrastructure setup, production deployment, and training.",
      },
    ],
  },
  clauseScores: {
    scores: [
      { clause: "Clause 1 - Fees and Payment", score: 58, verdict: "caution", rationale: "Payment tied to approval with no defined acceptance deadline." },
      { clause: "Clause 2 - Timeline", score: 42, verdict: "danger", rationale: "Uncapped penalty and no force majeure provision." },
      { clause: "Clause 3 - Milestones", score: 65, verdict: "caution", rationale: "Missing approval criteria, risk of payment blocking." },
      { clause: "Clause 4 - Intellectual Property", score: 72, verdict: "caution", rationale: "Clear IP transfer but confidentiality lacks duration." },
      { clause: "Clause 5 - Termination", score: 55, verdict: "caution", rationale: "Unbalanced unilateral termination conditions." },
      { clause: "Jurisdiction", score: 80, verdict: "safe", rationale: "Jurisdiction properly defined, no arbitration clause." },
      { clause: "General Provisions", score: 60, verdict: "caution", rationale: "No mandatory mediation before litigation." },
    ],
  },
  deployPlan: {
    steps: [
      { label: "Contract Uploaded", status: "done", detail: "contract-v2.pdf" },
      { label: "AI Risk Audit", status: "done", detail: "5 clauses reviewed, 2 accepted" },
      { label: "Milestones Configured", status: "done", detail: "4 milestones, $15,000 total" },
      { label: "Publish and Configure Sentinel", status: "current", detail: "Deploy escrow on Base Sepolia" },
    ],
    parties: [
      { name: "Suasuna Clinic Ltd", role: "Client", wallet: "0x1234...abcd" },
      { name: "DevStudio Technology LLC", role: "Developer", wallet: "0x5678...ef01" },
    ],
    milestoneSummary: [
      { name: "Design System & Prototypes", value: "$3,000", deadline: "2026-01-30" },
      { name: "Frontend Development", value: "$4,500", deadline: "2026-02-19" },
      { name: "Backend & API", value: "$5,000", deadline: "2026-03-11" },
      { name: "Deploy & Launch", value: "$2,500", deadline: "2026-03-26" },
    ],
    escrowTotal: "$15,000",
    network: "Base Sepolia",
    standard: "ERC-8004",
  },
};
