import type { ParsedContract } from "@/lib/schemas/contract-parse";

export const DEMO_PARSED: ParsedContract = {
  header: {
    subject: "Development of a medical scheduling system with CRM module, WhatsApp integration and administrative panel for patient management at Suasuna Clinic.",
    parties: [
      {
        role: "Client",
        name: "Clínica Suasuna Ltda",
        identifier: "12.345.678/0001-90",
        representative: "Dr. Ernani Suasuna, Diretor Clínico",
        city: "Recife-PE",
        initials: "CS",
      },
      {
        role: "Developer",
        name: "DevStudio Ltda",
        identifier: "98.765.432/0001-10",
        representative: "Michael Santos, Diretor Técnico",
        city: "Recife-PE",
        initials: "DL",
      },
    ],
    payment: {
      total: "R$ 15.000,00",
      terms: "Pagamento dividido em 4 parcelas vinculadas à entrega dos milestones, via transferência bancária, em até 5 dias úteis após a aprovação de cada milestone pela CONTRATANTE.",
    },
    timeline: {
      start: "2026-01-15",
      end: "2026-03-26",
      durationDays: 70,
    },
    jurisdiction: "Foro da Comarca de Recife-PE",
  },
  risks: {
    risks: [
      {
        id: "r1",
        clause: "Cláusula 2.2",
        title: "Multa por atraso sem limite máximo",
        description: "A multa de 2% ao mês sobre o valor restante não tem teto definido, criando exposição financeira ilimitada para a CONTRATADA.",
        severity: "high",
        originalText: "Atrasos superiores a 15 dias úteis por parte da CONTRATADA incorrerão em multa de 2% ao mês sobre o valor restante, sem limite máximo.",
        suggestion: "Adicionar cláusula limitando a multa total a no máximo 20% do valor contratado.",
      },
      {
        id: "r2",
        clause: "Cláusula 4.1",
        title: "Confidencialidade vaga e por prazo indeterminado",
        description: "A obrigação de sigilo não especifica prazo de vigência nem categorias de informação protegida, podendo gerar disputas futuras.",
        severity: "high",
        originalText: "As partes se comprometem a manter sigilo sobre todas as informações trocadas durante a execução deste contrato.",
        suggestion: "Definir prazo explícito (ex: 2 anos após o término) e listar categorias de informação sensível.",
      },
      {
        id: "r3",
        clause: "Cláusula 5.1",
        title: "Critérios de aprovação de milestone indefinidos",
        description: "Não há definição clara do que constitui aprovação de cada milestone, deixando margem para recusa arbitrária de pagamento.",
        severity: "high",
        originalText: "O pagamento será realizado após aprovação de cada milestone pela CONTRATANTE.",
        suggestion: "Incluir critérios objetivos de aceite e prazo máximo para aprovação (ex: 5 dias úteis).",
      },
      {
        id: "r4",
        clause: "Cláusula 3",
        title: "Ausência de cláusula de force majeure",
        description: "O contrato não prevê situações de caso fortuito ou força maior que possam impactar os prazos de entrega.",
        severity: "medium",
        originalText: "O prazo total para execução é de 70 (setenta) dias corridos.",
        suggestion: "Incluir cláusula padrão de força maior com prazo de notificação de 48h.",
      },
      {
        id: "r5",
        clause: "Geral",
        title: "Sem cláusula de resolução de disputas",
        description: "O contrato menciona foro mas não prevê etapa de mediação prévia, o que pode encarecer e atrasar a resolução de conflitos.",
        severity: "medium",
        originalText: "Foro da Comarca de Recife-PE.",
        suggestion: "Adicionar cláusula de mediação obrigatória prévia ao litígio com prazo de 30 dias.",
      },
      {
        id: "r6",
        clause: "Cláusula 1.2",
        title: "Prazo de pagamento sujeito à aprovação subjetiva",
        description: "Os 5 dias úteis para pagamento só começam após aprovação, que não tem prazo definido para ocorrer.",
        severity: "medium",
        originalText: "em até 5 dias úteis após a aprovação de cada milestone pela CONTRATANTE.",
        suggestion: "Estabelecer que milestone é automaticamente aprovado se não houver feedback em 5 dias úteis.",
      },
      {
        id: "r7",
        clause: "Cláusula 2.1",
        title: "Início do prazo dependente de ação da contratante",
        description: "O contrato não define claramente o que constitui início oficial do projeto, podendo gerar conflito sobre quando o prazo começa a contar.",
        severity: "low",
        originalText: "com início em 15/01/2026",
        suggestion: "Adicionar condição de início (ex: recebimento do primeiro pagamento ou assinatura digital).",
      },
    ],
  },
  milestones: {
    milestones: [
      {
        id: "m1",
        name: "Design System e Protótipos",
        value: 3000,
        deadline: "2026-01-30",
        deliverables: "Entrega de wireframes, design system e protótipos navegáveis.",
      },
      {
        id: "m2",
        name: "Frontend Development",
        value: 4500,
        deadline: "2026-02-19",
        deliverables: "Implementação das telas e componentes.",
      },
      {
        id: "m3",
        name: "Backend e API",
        value: 5000,
        deadline: "2026-03-11",
        deliverables: "Desenvolvimento da API, banco de dados e integrações.",
      },
      {
        id: "m4",
        name: "Deploy e Launch",
        value: 2500,
        deadline: "2026-03-26",
        deliverables: "Configuração de infraestrutura, deploy em produção e treinamento.",
      },
    ],
  },
  clauseScores: {
    scores: [
      { clause: "Cláusula 1 - Valor e Pagamento", score: 58, verdict: "caution", rationale: "Pagamento vinculado à aprovação sem prazo definido para o aceite." },
      { clause: "Cláusula 2 - Prazo", score: 42, verdict: "danger", rationale: "Multa sem teto e sem previsão de força maior." },
      { clause: "Cláusula 3 - Milestones", score: 65, verdict: "caution", rationale: "Critérios de aprovação ausentes, risco de bloqueio de pagamento." },
      { clause: "Cláusula 4 - Propriedade Intelectual", score: 72, verdict: "caution", rationale: "Transferência clara mas confidencialidade sem prazo." },
      { clause: "Cláusula 5 - Rescisão", score: 55, verdict: "caution", rationale: "Condições de rescisão unilateral desequilibradas." },
      { clause: "Foro e Jurisdição", score: 80, verdict: "safe", rationale: "Foro definido corretamente, sem cláusula arbitral." },
      { clause: "Disposições Gerais", score: 60, verdict: "caution", rationale: "Ausência de mediação prévia ao litígio." },
    ],
  },
  deployPlan: {
    steps: [
      { label: "Contract Uploaded", status: "done", detail: "contract-v2.pdf" },
      { label: "AI Risk Audit", status: "done", detail: "5 clauses reviewed, 2 accepted" },
      { label: "Milestones Configured", status: "done", detail: "4 milestones, $3,800 total" },
      { label: "Publish and Configure Sentinel", status: "current", detail: "Deploy escrow on Base Sepolia" },
    ],
    parties: [
      { name: "Clínica Suasuna Ltda", role: "Client", wallet: "0x1234...abcd" },
      { name: "DevStudio Ltda", role: "Developer", wallet: "0x5678...ef01" },
    ],
    milestoneSummary: [
      { name: "Design System e Protótipos", value: "R$ 3.000", deadline: "2026-01-30" },
      { name: "Frontend Development", value: "R$ 4.500", deadline: "2026-02-19" },
      { name: "Backend e API", value: "R$ 5.000", deadline: "2026-03-11" },
      { name: "Deploy e Launch", value: "R$ 2.500", deadline: "2026-03-26" },
    ],
    escrowTotal: "$15000",
    network: "Base Sepolia",
    standard: "ERC-8004",
  },
};
